---
# handlers file for lamp
- name: start apache
  become: yes
  service:
    name: apache2
    state: started

- name: start httpd
  become: yes
  service:
    name: httpd
    state: started

- name: start mariadb
  become: yes
  service:
    name: mysqld
    state: started